### ISSUE TITLE
Current code tree doesn't build... Am I missing something?

### ISSUE THREAD

**Issue by davewthompson** [openfin/fin-hypergrid#330]
All,

Doing a fresh clone from the current repo and I get test failures and uglify errors:

$ git clone https://github.com/openfin/fin-hypergrid.git
$ npm install
$ gulp build

...yields four test failures.
If I remove the test from the build step in the gulpfile.js, there are errors in the uglify method.

Windows 10 x64, Git Bash, and latest versions of Node and NPM. Am I missing something?

Thanks,

Dave

**Comment by Dwaynekj** [comment]
Hello Dave,

Would you mind pasting the errors here for us to see?

**Comment by davewthompson** [comment]
Sure, here they are:

```[10:45:29] Starting 'lint'...
[10:45:33] Finished 'lint' after 3.72 s
[10:45:33] Starting 'images'...
[10:45:33] Finished 'images' after 271 ms
[10:45:33] Starting 'html-templates'...
[10:45:33] Finished 'html-templates' after 41 ms
[10:45:33] Starting 'css-templates'...
[10:45:33] Finished 'css-templates' after 10 ms
[10:45:33] Starting 'test'...


  Base
    Module expected shape
      √ Should have the instance shape
    extend
      √ Should create a new constructor
      √ Should extend with HypergridError
      √ Should extend with deprecated
    HypergridError
      √ should assign the message

  CSS
    Module expected shape
      1) Should have theinstance shape
      2) Should not be empty

  HTML
    Module expected shape
      3) Should have strings keys
      4) Should not be empty

  Image
    Module expected shape
      √ Should have the instance shape
      √ Image Objects have src properties
    checkbox
      √ Should return the checked image
      √ Should return the unchecked image
    filter
      √ Should return the filter-on image
      √ Should return the unchecked image

  SelectionModel
    Module expected shape
      √ Should have the instance shape


  12 passing (64ms)
  4 failing

  1) CSS Module expected shape Should have theinstance shape:
     C:\dev\git\fin-hypergrid\css\index.js:4
'.hypergrid-input {
^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
      at Object.exports.runInThisContext (vm.js:76:16)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (C:\dev\git\fin-hypergrid\test\css-test.js:20:23)
      at callFn (C:\dev\git\fin-hypergrid\node_modules\mocha\lib\runnable.js:326:21)

  2) CSS Module expected shape Should not be empty:
     C:\dev\git\fin-hypergrid\css\index.js:4
'.hypergrid-input {
^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
      at Object.exports.runInThisContext (vm.js:76:16)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (C:\dev\git\fin-hypergrid\test\css-test.js:28:23)
      at callFn (C:\dev\git\fin-hypergrid\node_modules\mocha\lib\runnable.js:326:21)

  3) HTML Module expected shape Should have strings keys:
     C:\dev\git\fin-hypergrid\html\index.js:4
'<li>
^^^^^
SyntaxError: Invalid or unexpected token
      at Object.exports.runInThisContext (vm.js:76:16)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (C:\dev\git\fin-hypergrid\test\html-test.js:27:24)
      at callFn (C:\dev\git\fin-hypergrid\node_modules\mocha\lib\runnable.js:326:21)

  4) HTML Module expected shape Should not be empty:
     C:\dev\git\fin-hypergrid\html\index.js:4
'<li>
^^^^^
SyntaxError: Invalid or unexpected token
      at Object.exports.runInThisContext (vm.js:76:16)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (C:\dev\git\fin-hypergrid\test\html-test.js:35:24)
      at callFn (C:\dev\git\fin-hypergrid\node_modules\mocha\lib\runnable.js:326:21)



[10:45:34] 'test' errored after 519 ms
[10:45:34] Error in plugin 'gulp-mocha'
Message:
    4 tests failed.
[10:45:34] 'build' errored after 4.57 s
[10:45:34] Error in plugin 'run-sequence(test)'
Error
    at finish (C:\dev\git\fin-hypergrid\node_modules\run-sequence\index.js:56:13)
    at Gulp.onError (C:\dev\git\fin-hypergrid\node_modules\run-sequence\index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\dev\git\fin-hypergrid\node_modules\orchestrator\index.js:264:8)
    at C:\dev\git\fin-hypergrid\node_modules\orchestrator\index.js:275:23
    at finish (C:\dev\git\fin-hypergrid\node_modules\orchestrator\lib\runTask.js:21:8)
    at Stream.<anonymous> (C:\dev\git\fin-hypergrid\node_modules\orchestrator\lib\runTask.js:52:4)
    at Stream.f (C:\dev\git\fin-hypergrid\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at emitOne (events.js:101:20)
```

**Comment by Dwaynekj** [comment]
This is odd. @katierose4 and I just did a fresh install (of node and the grid) on our Window 10 instance with no issues. Maybe we can setup a screen share via skype for sometime this afternoon. I am eastern time. My skype is dj_openfin

**Comment by davewthompson** [comment]
Let me do a fresh install in a Windows 10 VM and get back to you...

**Comment by Dwaynekj** [comment]
How did this go?

**Comment by stofte** [comment]
I'm also seeing the same thing, Windows 10 x64,

npm 3.10.8
node 6.9.1 (x64)
gulp 1.2.2 (installed 

gulp output is here: https://gist.github.com/stofte/995bc786e7e92eb08347f0fbd2adc9b3

Taking a look at css/index.js which is one of the files that fails, I'm seeing this:
https://gist.github.com/stofte/050f681771b659eb87f7a51d2a1781cc
which leads me to assume that the template function in gulpfile.js has issues with newlines (autoclrf setting messing around?)

**Comment by Dwaynekj** [comment]
@stofte Sorry for the delay. Is this still an issue?

**Comment by stofte** [comment]
@Dwaynekj Yes, I'm still seeing the same error as @davewthompson

**Comment by Dwaynekj** [comment]
@davewthompson We haven't been actively testing on node 6 as of yet. Leveraging nvm could your try node 5 to see if that works?

**Comment by stofte** [comment]
I installed 5.12.0 and the error/output is the same as before.

**Comment by Dwaynekj** [comment]
@stofte I was able to build Hypergrid from scratch with no issue. I think it be best to do a skype/webex so as to get you resolved as soon as asap. I also to apologize with response time, we have been busy completing our last sprint

**Comment by stofte** [comment]
@Dwaynekj Response times can be trying in these holiday times :)

I'm open for arranging a session, but something with desktop sharing is probably best. I'm not really familiar with options, so I'll let you decide.

**Comment by Dwaynekj** [comment]
Skype has good desktop sharing. Are you open to a Skype call between 10-12 EST tomorrow. My username is dj_openfin

**Comment by Dwaynekj** [comment]
@stofte LMK if your open to a call this week

**Comment by vrut57** [comment]
I'm running into errors during the build as well. 

-git clone
-npm install
-gulp build (with test removed from the gulpfile)


[11:57:39] Starting 'lint'...
[11:57:47]
add-ons\dialog-ui\css\index.js
  4:36  error  Parsing error: Unexpected token ILLEGAL

add-ons\dialog-ui\html\index.js
  4:8  error  Parsing error: Unexpected token ILLEGAL

✖ 2 problems (2 errors, 0 warnings)

[11:57:47] 'lint' errored after 7.77 s
[11:57:47] ESLintError in plugin 'gulp-eslint'
Message:
    Failed with 2 errors
[11:57:47] 'build' errored after 7.78 s
[11:57:47] ESLintError in plugin 'run-sequence(lint)'
Error
    at finish (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid\node_modules\run-sequence\index.js:56:13)
    at Gulp.onError (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid\node_modules\run-sequence\index.js:67:4
)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid\node_modules\orchest
rator\index.js:264:8)
    at C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid\node_modules\orchestrator\index.js:275:23
    at finish (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid\node_modules\orchestrator\lib\runTask.js:21:8
)
    at Transform.<anonymous> (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid\node_modules\orchestrator\lib\
runTask.js:52:4)
    at Transform.f (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid\node_modules\once\once.js:17:25)
    at emitOne (events.js:101:20)
PS C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid>

**Comment by Dwaynekj** [comment]
@vrut57 Could you try the develop branch, it will be the alpha in the next day or so?

**Comment by vrut57** [comment]
Thanks for the quick reply @Dwaynekj 

I'm still having issues after switching to the Develop branch. The tests fail, but even if I temporarily remove them, browserify runs into an issue with an unterminated string constant which seems like the exact issue @stofte was having above.


```
[16:26:43] Starting 'lint'...
[16:26:47] Finished 'lint' after 3.88 s
[16:26:47] Starting 'images'...
[16:26:47] Finished 'images' after 179 ms
[16:26:47] Starting 'css-templates'...
[16:26:47] Finished 'css-templates' after 15 ms
[16:26:47] Starting 'add-ons'...
[16:26:48] Finished 'add-ons' after 332 ms
[16:26:48] Starting 'browserify'...
[16:26:51] { SyntaxError:
C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\css\index.js:4
',hypergrid-container {
^
ParseError: Unterminated string constant
    at wrapWithPluginError (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_modul
es\gulp-browserify\index.js:44:10)
    at Stream.<anonymous> (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_module
s\gulp-browserify\index.js:123:28)
    at Stream.<anonymous> (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_module
s\browserify\index.js:344:22)
    at emitOne (events.js:101:20)
    at Stream.emit (events.js:188:7)
    at Transform.onerror (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_modules
\stream-combiner\index.js:29:18)
    at emitOne (events.js:101:20)
    at Transform.emit (events.js:188:7)
    at onwriteError (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_modules\brow
serify\node_modules\readable-stream\lib\_stream_writable.js:250:10)
    at onwrite (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_modules\browserif
y\node_modules\readable-stream\lib\_stream_writable.js:268:5)
  plugin: 'gulp-browserify',
  showStack: false,
  name: 'SyntaxError',
  message: '\nC:\\Program Files\\apache-tomcat-8.0.30\\webapps\\fin-hypergrid-develop\\fin-hypergrid\\css\\index.js:4\n\
'.hypergrid-container {\r\',\n^\nParseError: Unterminated string constant',
  fileName: undefined,
  lineNumber: undefined,
  stack: [Getter/Setter] }

events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError:
C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\css\index.js:4
',hypergrid-container {
^
ParseError: Unterminated string constant
    at wrapWithPluginError (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_modul
es\gulp-browserify\index.js:44:10)
    at Stream.<anonymous> (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_module
s\gulp-browserify\index.js:123:28)
    at Stream.<anonymous> (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_module
s\browserify\index.js:344:22)
    at emitOne (events.js:101:20)
    at Stream.emit (events.js:188:7)
    at Transform.onerror (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_modules
\stream-combiner\index.js:29:18)
    at emitOne (events.js:101:20)
    at Transform.emit (events.js:188:7)
    at onwriteError (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_modules\brow
serify\node_modules\readable-stream\lib\_stream_writable.js:250:10)
    at onwrite (C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid\node_modules\browserif
y\node_modules\readable-stream\lib\_stream_writable.js:268:5)
PS C:\Program Files\apache-tomcat-8.0.30\webapps\fin-hypergrid-develop\fin-hypergrid>

```

**Comment by Dwaynekj** [comment]
What is your environment?

**Comment by Dwaynekj** [comment]
This seems to be resolved with Node >= 5.0.0. Can you give that a try through NVM

**Comment by vrut57** [comment]
I'm running node v 6.9.4, windows 8.1 64-bit, npm v 3.10.8, and gulp  v3.9.1

**Comment by davewthompson** [comment]
Sorry for my very tardy response! I still get this issue.

Windows 10 x64

node --version
v6.9.4

npm --version
3.10.10

gulp --version
[11:37:16] CLI version 3.9.1
[11:37:16] Local version 3.9.1

**Comment by Dwaynekj** [comment]
ok thanks for the info, we will look into this

**Comment by Dwaynekj** [comment]
Everyone can take  alook at the provided workaround here: https://github.com/openfin/fin-hypergrid/issues/579#issuecomment-291951540
